/**
 * 应用常量定义
 */

/** 状态栏高度（vp）的AppStorage键名 */
export const TOP_RECT_HEIGHT = 'topRectHeight'

/** 底部导航栏高度（vp）的AppStorage键名 */
export const BOTTOM_RECT_HEIGHT = 'bottomRectHeight'

/** 挖孔屏上边界坐标（vp）的AppStorage键名 */
export const CUTOUT_TOP = 'cutoutTop'

/** 挖孔屏左边界坐标（vp）的AppStorage键名 */
export const CUTOUT_LEFT = 'cutoutLeft'

/** 挖孔屏宽度（vp）的AppStorage键名 */
export const CUTOUT_WIDTH = 'cutoutWidth'

/** 挖孔屏高度（vp）的AppStorage键名 */
export const CUTOUT_HEIGHT = 'cutoutHeight'
